### ISSUE TITLE
Define the flow of water within the landform node editor

### ISSUE THREAD

**Issue by optimumtact** [m00nl1ght-dev/GeologicalLandforms#2]
Is there anyway to give water the flowing property so that it can be used for watermills etc?

I'm could not find anything in the default nodes or the existing landforms that seemed like it would provide such a thing.

**Comment by m00nl1ght-dev** [comment]
River-related features, such as flowing water, are planned and will be added in a future update.

**Comment by optimumtact** [comment]
Thanks, glad to hear, the node system in this is extremely cool and I was able to define a landform very quickly once I understood it. Thank you for your work on this.

**Comment by m00nl1ght-dev** [comment]
The water flow output node has now been added in [v1.6.3](https://github.com/m00nl1ght-dev/GeologicalLandforms/releases/tag/v1.6.3)

**Comment by optimumtact** [comment]
awesome, thanks
