### ISSUE TITLE
Placing landforms directly is inaccessible

### ISSUE THREAD

**Issue by SokyranTheDragon** [m00nl1ght-dev/GeologicalLandforms#4]
Trying to access the functionality of placing the landforms directly on the map seems to be inaccessible.

From what I've gathered looking at the code - it should appear under the terrain tab after selecting a tile on the map, right under the button to find one. It should only appear if dev mode is enabled, as well as the respective option in settings is enabled. The actual behavior is that there's no button for it.

My best assumption is related to this line of code:
https://github.com/m00nl1ght-dev/GeologicalLandforms/blob/7157196c8d5811bbe82189fa537c674bad063d59/Sources/GeologicalLandformsMod/TerrainTabUI.cs#L43

And to be more precise - if I understand correctly, it checks if the tile contains a landform (not null), and it's not locked. However, this only means it would only be possible to replace existing ones (as long as they're not locked) - while I assume the check would be that the tile does not contain one, or if it does - it's not locked (allowing placement of new ones).

**Comment by SokyranTheDragon** [comment]
Also, as an additional note - this also affects the current Steam release.

**Comment by m00nl1ght-dev** [comment]
I just tested with the latest Steam version, and the button appears and works for me as expected. So something specific must be happening on your end that prevents it from appearing. For example, it might be another mod you have installed that breaks it. Have you tried with only Geological Landforms installed and no other mods?

Regarding your assumption about the code:

> it checks if the tile contains a landform (not null)
No, `landformData` is a `WorldComponent` that stores information about which landform is placed on which world tile. It must be present to be able to place landforms, hence the null check. If it's missing, then some other mod is messing with your WorldComponents. Again, please try again with all other mods disabled.

**Comment by m00nl1ght-dev** [comment]
Ok, if it happens again, and you figure out which mod causes it, please let me know, I'd be interested in creating a compatibility patch if possible.
